- .vitebook/config.ts
- .vitebook/dist/index.html
- Fixed Learn More link in config
- Fixed Learn More link in index
Fixes 
Connects 
> Learn More link fix

- .vitebook/config.ts
- src/motor-sdk/android/authenticate.md
- src/motor-sdk/android/buckets.md
- src/motor-sdk/android/create-object.md
- src/motor-sdk/android/documents.md
- src/motor-sdk/android/get-object.md
- src/motor-sdk/android/getting-started.md
- src/motor-sdk/android/schemas.md
- src/motor-sdk/android/updating-buckets.md
> added rough draft of each section

- .vitebook/config.ts
- src/motor-sdk/android/bucket-reference.md
- src/motor-sdk/android/document-builder-reference.md
- src/motor-sdk/android/motoroid-reference.md
- src/motor-sdk/android/object-builder-reference.md
- src/motor-sdk/go/overview.md
- src/motor-sdk/overview.md
> Add reference sections

- src/highway/modules/objects.md
- Item 1
- Item 2
Fixes 
Connects 
> updates to object docs

- src/motor-sdk/speedway/cli/cli-overview.md
- src/motor-sdk/speedway/getting-started.md
- Item 1
- Item 2
Fixes 
Connects 
> added urls to cli-overview

- src/motor-sdk/speedway/cli/cli-commands.md
- src/motor-sdk/speedway/cli/cli-overview.md
- src/motor-sdk/speedway/getting-started.md
- Item 1
- Item 2
Fixes 
Connects 
> update to cli docs

- src/modules/registry.md
- Item 1
- Item 2
Fixes 
Connects 
> update to registry docs

- src/motor-sdk/speedway/getting-started.md
- Item 1
- Item 2
Fixes 
Connects 
> update of URL from branch to main

- README.md
- package.json
- Addition of mv operation to `dist` on build
- Item 1
- Item 2
Fixes 
Connects 
> addition of move operation in build script to dist

- docs/highway/modules/buckets.md
- docs/highway/modules/objects.md
- docs/highway/modules/registry.md
- docs/highway/modules/schemas.md
- Schemas
- Objects
Fixes 
Connects 
> Ma sonr changes 2

- docs/what-is-sonr.mdx
Removed Youtube video and added concise description
Note: Once Fiverr video completed on September 5th, will be added in. 
Fixes 
Connects 
> Replaced Youtube video with description

- docusaurus.config.js
- Item 1
- Item 2
Fixes 
Connects 
> Replace "Integrate" with SDKs

- docs/what-is-sonr.mdx
- docusaurus.config.js
- src/pages/index.js
Changed Let's get started to JS string literal (with double-quotes) to add apostrophe
- Item 1
- Item 2
Fixes 
Connects 
> PennApps docs review

- docs/guides/auth/login.mdx
- docs/guides/auth/register.mdx
- docs/guides/data/documents.mdx
- docs/guides/data/schemas.mdx
- docs/guides/storage/buckets.mdx
- docs/guides/storage/fetch.mdx
- Updates to Go examples in `getting started`
- Login
- Register
- Schemas
- Buckets
- Item 1
- Item 2
Fixes 
Connects 
> Updates to go examples

- docs/guides/auth/login.mdx
- docs/guides/auth/register.mdx
- docs/guides/data/documents.mdx
- docs/guides/data/schemas.mdx
- docs/guides/storage/buckets.mdx
- docs/guides/storage/fetch.mdx
- Item 1
- Item 2
Fixes 
Connects 
> Merge into main

- blog/2022-09-07-flutter-guide/index.mdx
- docs/guides/setup.mdx
Adds more to the todo app
- Item 1
- Item 2
Fixes 
Connects 
> Stage 2 Flutter Example Blog

- docs/guides/install.mdx
Added "Build From Source" Instructions in the "Install Guide" 
- Install Guide
N/A
N/A
Fixes 
Connects 
> added build from source

- blog/2022-09-07-flutter-guide/index.mdx
- docs/guides/data/documents.mdx
- docs/guides/storage/buckets.mdx
- Swaps Java for android
- Fixes order on Getting Started
Fixes #47 
Connects 
> Standardize the order of the tab components

- docs/guides/auth/login.mdx
- docs/guides/auth/register.mdx
- docs/guides/data/documents.mdx
- docs/guides/data/schemas.mdx
- docs/guides/setup.mdx
- docs/guides/storage/buckets.mdx
- docs/guides/storage/fetch.mdx
Ordering of Flutter
Fixes 
Connects 
> Ordering fixed (CLI, Flutter,..)

- blog/2022-09-07-flutter-guide/index.mdx
- docs/guides/auth/login.mdx
- docs/guides/auth/register.mdx
- docs/guides/data/documents.mdx
- docs/guides/define.mdx
- docs/guides/setup.mdx
- docs/guides/storage/buckets.mdx
- docs/main.mdx
- docs/tools/speedway/install.mdx
Docs updates for Calhacks and HackHarvard
> started calhard updates
